# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PR Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./Source
      run: dotnet restore SvcCom.sln
    - name: Build
      working-directory: ./Source
      run: dotnet build SvcCom.sln --no-restore
    - name: Test
      working-directory: ./Source
      run: dotnet test SvcCom.sln --no-build --verbosity normal
